### ISSUE TITLE
Document how to run examples

### ISSUE THREAD

**Issue by JosiahParry** [ambiorix-web/ambiorix-examples#5]
I've opened up 09_goals and am trying to run this. 
After restoring it isn't clear which script to run to start the app. So, I've navigated to `backend/server.R` and tried to run this. This fails with 
```
Error in `box::use()`:
! unable to load module “./helpers/get_port”; not found in 
```
so, i change the wd to `backend` and try again which results in 
```
 No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling hello on 'localhost:27017']
```

**Comment by kennedymwavu** [comment]
Hi @JosiahParry ,
Thanks for that.
The [updated README](https://github.com/kennedymwavu/ambiorix-examples/tree/main/09_goals) should be okay now.
